from PyQt5.QtGui import QColor

SPLINE_WINDOW_X = 40
SPLINE_WINDOW_Y = 100
SPLINE_WINDOW_WIDTH = 1120
SPLINE_WINDOW_HEIGHT = 553

SPLINE_DRAWING_PANEL_X = 50
SPLINE_DRAWING_PANEL_Y = 40
SPLINE_DRAWING_PANEL_WIDTH = 800
SPLINE_DRAWING_PANEL_HEIGHT = 500

DEFAULT_CURVE_COLOR = QColor(170, 0, 255)
DEFAULT_POINT_COLOR = QColor(255, 255, 255)

SPLINE_SETTINGS_PANEL_CURVE_X = SPLINE_DRAWING_PANEL_X + 815
SPLINE_SETTINGS_PANEL_CURVE_Y = SPLINE_DRAWING_PANEL_Y

SPLINE_SETTINGS_PANEL_POINT_X = SPLINE_DRAWING_PANEL_X + 815
SPLINE_SETTINGS_PANEL_POINT_Y = 298

SPLINE_SETTINGS_PANEL_WIDTH = 243
SPLINE_SETTINGS_PANEL_HEIGHT = 242